spring:
  r2dbc:
    url: r2dbc:mysql://${mysql.host}:3306/auth
    username: ${RDBMS_USERNAME}
    password: ${RDBMS_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    url: jdbc:mysql://${mysql.host}:3306/auth
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    locations: classpath:db/migration

mysql:
  host: ${RDBMS_URL}

find-my-pet:
  oauth2:
    google:
      client-id: ${FMP_GOOGLE_CLIENT_ID}
      client-secret: ${FMP_GOOGLE_CLIENT_SECRET}
    kakao:
      client-id: ${FMP_KAKAO_CLIENT_ID}

pocket-fit:
  oauth:
    kakao:
      client-id: ${PF_KAKAO_CLIENT_ID}