spring:
  data:
    redis:
      host: localhost
      password: healthgood1!
      port: 6379
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/auth
    username: root
    password: 1234

mysql:
  host: localhost

jwt:
  access-token:
    secret-key: ${ACCESS_SECRET_KEY:qwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwqwq}
    expire-millis: ${ACCESS_EXPIRE_MILLIS:100000000000}
  refresh-token:
    secret-key: ${REFRESH_SECRET_KEY:asasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasaasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasaasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasasa}
    expire-millis: ${REFRESH_EXPIRE_MILLIS:1000000000000000}