spring:
  profiles:
    active: dev
  application:
    name: ${spring.profiles.active}-auth
  main:
    web-application-type: reactive
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false
  r2dbc:
    url: r2dbc:mysql://${mysql.host}:3306/auth?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${RDBMS_USERNAME}
    password: ${RDBMS_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    url: jdbc:mysql://${mysql.host}:3306/auth
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    locations: classpath:db/migration
  cloud:
    compatibility-verifier:
      enabled: false
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
pyroscope:
  address: ${PYROSCOPE_SERVER_ADDRESS}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: false
    hostname: auth-server
logging:
  level:
    org:
      springframework:
        security: debug
#logging:
#  level:
#    root: debug
mysql:
  host: ${RDBMS_URL}

# custom env
jwt:
  access-token:
    secret-key: ${ACCESS_SECRET_KEY}
    expire-millis: ${ACCESS_EXPIRE_MILLIS}
  refresh-token:
    secret-key: ${REFRESH_SECRET_KEY}
    expire-millis: ${REFRESH_EXPIRE_MILLIS}
grpc:
  server:
    port: 9090

server:
  http2:
    enabled: true